#!/usr/bin/python

import pymongo, os, datetime
db = pymongo.Connection(os.environ.get("GAMETAG_MONGODB", "localhost"), tz_aware=True)['gametag']

db.events.remove({'genericEnrollment': True}, safe=True)

for age in ['adult', 'elementary', 'middle', 'high']:
    for i in range(1, 100+1):
        db.events.insert(dict(
                t=datetime.datetime(2013,1,1),
                type="enroll",
                user="https://gametag.bigast.com/users/%s%s" % (age, i),
                label="%s %s" % (age.capitalize(), i),
                ageCategory=age,
                genericEnrollment=True
                ))
                
